import json
import sys
import time

try:
    ticks_ms = time.ticks_ms
    ticks_diff = time.ticks_diff
    ticks_add = time.ticks_add
except AttributeError:

    def ticks_ms():
        return int(time.time() * 1000)

    def ticks_diff(a, b):
        return a - b

    def ticks_add(a, b):
        return a + b


try:
    import traceback
except ImportError:
    traceback = None


def _print_exception(exc):
    if hasattr(sys, "print_exception"):
        sys.print_exception(exc)
    elif traceback:
        traceback.print_exception(type(exc), exc, getattr(exc, "__traceback__", None))
    else:
        print("Exception: %r" % (exc,))


def _to_str(value):
    if isinstance(value, bytes):
        return value.decode()
    return str(value)


class Device:
    def __init__(
        self,
        device_name,
        discovery_prefix='homeassistant',
        retain_discovery=False,
        connect_timeout=10,
        reconnect_min_ms=1000,
        reconnect_max_ms=60000,
        **kwargs,
    ):
        """
        Initializes the device with the given name and optional keyword arguments passed
        directly to the Home Assistant config.

        @param device_name: The name of the device.
        @type device_name: str

        @param discovery_prefix: The prefix used for discovery topics. Defaults to 'homeassistant'.
        @type discovery_prefix: str, optional

        @param retain_discovery: Retain MQTT discovery messages. Defaults to False.
        @type retain_discovery: bool, optional

        @param connect_timeout: Optional socket timeout in seconds for umqtt.simple versions supporting it.
        @type connect_timeout: int, optional

        @param reconnect_min_ms: Initial reconnect backoff in milliseconds.
        @type reconnect_min_ms: int, optional

        @param reconnect_max_ms: Maximum reconnect backoff in milliseconds.
        @type reconnect_max_ms: int, optional

        @param kwargs: Additional keyword arguments to be added to the configuration of the device.

        @note: The device ID is generated by replacing spaces in the device name with underscores
        and converting to lowercase.
        """
        self.name = device_name
        self.id = self.name.replace(' ', '_').lower()  # TODO: ö, ä, ü, ... not handled!
        self.discovery_prefix = discovery_prefix
        self.retain_discovery = retain_discovery
        self.connect_timeout = connect_timeout
        self.reconnect_min_ms = reconnect_min_ms
        self.reconnect_max_ms = reconnect_max_ms
        self.will_topic = '%s/availability/%s' % (self.discovery_prefix, self.id)
        self.ha_status_topic = '%s/status' % self.discovery_prefix
        self.ha_status = None  # Last received HA status ("online" / "offline")
        self.device = kwargs
        self.device['name'] = self.name
        self.device['ids'] = self.id
        self._mqttc = None
        self._entities = []
        self._subscriptions = {}
        self._connected = False
        self._connecting = False
        self._restoring = False
        self._disconnect_requested = False
        self._last_ping = ticks_ms()
        self._next_reconnect = ticks_ms()
        self._reconnect_delay = self.reconnect_min_ms
        self._ping_interval_ms = 30000
        self._echo_timeout_ms = 60000
        self._awaiting_echo = False
        self._echo_deadline = ticks_ms()
        self._last_echo = ticks_ms()
        self._robust_hooked = False
        self._robust_hooked_client = None
        self._robust_reconnecting = False
        self.subscribe(self.ha_status_topic, self._ha_status_callback)
        self.subscribe(self.will_topic, self._availability_callback)

    @property
    def is_connected(self):
        """
        @brief Returns True when the MQTT client is currently considered connected.
        """
        return self._connected

    def connect(self, mqttc):
        """
        @brief Connects to the MQTT broker and sets up the necessary configurations.

        @param mqttc: The MQTT client instance to be used for the connection.

        @return: True if the connection succeeded, False otherwise.

        This method stores the client, configures LWT and callbacks, attempts a clean
        session connection, and runs the common post-connect recovery routine. Failures
        are captured so callers can keep running and let loop() retry.
        """
        self._mqttc = mqttc
        self._disconnect_requested = False
        self._configure_client()
        ok = self._connect_client(clean_session=True)
        if ok:
            return self._on_connect()
        self._schedule_reconnect()
        return False

    def disconnect(self):
        """
        @brief Gracefully disconnects from MQTT and publishes retained offline availability.

        @return: True if the disconnect call completed without a network error, else False.
        """
        self._disconnect_requested = True
        ok = True
        if self._mqttc and self._connected:
            ok = self.publish(self.will_topic, 'offline', retain=True)
            try:
                self._mqttc.disconnect()
            except OSError:
                ok = False
            except Exception as exc:
                ok = False
                _print_exception(exc)
        self._connected = False
        self._awaiting_echo = False
        return ok

    def subscribe(self, topic, callback):
        """
        @brief Registers an MQTT subscription and callback.

        @param topic: MQTT topic to subscribe to.
        @type topic: str

        @param callback: Callable receiving the decoded message string.

        @return: True if the subscription is active or queued, False on immediate MQTT error.

        The subscription is remembered and restored after every reconnect. If the
        device is already connected, the MQTT subscribe call is performed immediately.
        """
        topic = _to_str(topic)
        self._subscriptions[topic] = callback
        if self._connected:
            return self._subscribe_now(topic)
        return True

    def publish(self, topic, payload, retain=False):
        """
        @brief Safely publishes an MQTT message.

        @param topic: MQTT topic.
        @param payload: Payload to publish.
        @param retain: Retain flag. Defaults to False.

        @return: True on success, False if disconnected or a network error occurred.
        """
        if not self._mqttc or not self._connected:
            return False
        try:
            self._raw_mqtt_call('publish', topic, payload, retain)
            return True
        except OSError:
            self._mark_disconnected()
            return False
        except Exception as exc:
            self._mark_disconnected()
            _print_exception(exc)
            return False

    def mqtt_callback(self, topic, msg):
        """
        @brief Callback function for handling incoming MQTT messages.

        @param topic: The topic of the received MQTT message (bytes or str).
        @param msg: The payload of the received MQTT message (bytes or str).

        Incoming messages are decoded and dispatched through the subscription
        registry. Exceptions from user callbacks are printed and do not escape.
        """
        decoded_topic = _to_str(topic)
        decoded_msg = _to_str(msg)
        callback = self._subscriptions.get(decoded_topic)
        if callback:
            try:
                callback(decoded_msg)
            except Exception as exc:
                _print_exception(exc)

    def loop(self):
        """
        @brief Main loop function to keep MQTT connected and process messages.

        @return: True if connected after this loop iteration, otherwise False.

        This method never raises because of MQTT network errors. When disconnected,
        it retries with exponential backoff. When connected, it performs keepalive
        ping, non-blocking message checks, and an availability echo liveness check.
        Call this frequently from the main loop, not from timer IRQs.
        """
        now = ticks_ms()
        if not self._mqttc:
            return False
        if not self._connected:
            if ticks_diff(now, self._next_reconnect) >= 0:
                if self._connect_client(clean_session=True) and self._on_connect():
                    return True
                self._schedule_reconnect()
            return False
        if self._awaiting_echo and ticks_diff(now, self._echo_deadline) > 0:
            self._mark_disconnected()
            return False
        if ticks_diff(now, self._last_ping) >= self._ping_interval_ms:
            if not self._safe_mqtt_call('ping'):
                return False
            self._last_ping = now
            self._send_liveness_probe()
        if not self._safe_mqtt_call('check_msg'):
            return False
        return self._connected

    def discover_all(self):
        """
        @brief (Re-)sends the discovery message for all entities to Home Assistant.

        This method iterates over all entities assigned to the device and calls
        their `discover` method to (re-)send the discovery message to Home Assistant.
        """
        ok = True
        for entity in self._entities:
            if not entity.discover():
                ok = False
        return ok

    def _configure_client(self):
        keepalive = getattr(self._mqttc, 'keepalive', 0) or 60
        self._ping_interval_ms = int(keepalive * 600)
        if self._ping_interval_ms <= 0:
            self._ping_interval_ms = 30000
        self._echo_timeout_ms = int(keepalive * 1000)
        if self._echo_timeout_ms <= 0:
            self._echo_timeout_ms = 60000
        try:
            self._mqttc.set_last_will(self.will_topic, 'offline', retain=True, qos=0)
        except TypeError:
            self._mqttc.set_last_will(self.will_topic, 'offline', retain=True)
        self._mqttc.set_callback(self.mqtt_callback)
        self._hook_robust_reconnect()

    def _connect_client(self, clean_session=True):
        if self._connecting:
            return False
        self._connecting = True
        try:
            try:
                self._mqttc.connect(clean_session=clean_session, timeout=self.connect_timeout)
            except TypeError:
                try:
                    self._mqttc.connect(clean_session=clean_session)
                except TypeError:
                    self._mqttc.connect()
            return True
        except OSError:
            self._close_socket()
            self._connected = False
            return False
        except Exception as exc:
            self._close_socket()
            self._connected = False
            _print_exception(exc)
            return False
        finally:
            self._connecting = False

    def _on_connect(self):
        self._connected = True
        self._reconnect_delay = self.reconnect_min_ms
        self._last_ping = ticks_ms()
        self._awaiting_echo = False
        # Announce availability last: Home Assistant may send commands as soon as it
        # sees "online", so subscriptions, discovery, and states must be restored first.
        # While restoring, the retained "offline" last will delivered on resubscribe must
        # not trigger an early "online" (see _availability_callback).
        self._restoring = True
        try:
            for topic in list(self._subscriptions.keys()):
                if not self._subscribe_now(topic):
                    return False
            self.discover_all()
            for entity in self._entities:
                entity.republish()
        finally:
            self._restoring = False
        if not self.publish(self.will_topic, 'online', retain=True):
            return False
        return self._connected

    def _subscribe_now(self, topic):
        try:
            try:
                self._raw_mqtt_call('subscribe', topic, 0)
            except TypeError:
                self._raw_mqtt_call('subscribe', topic)
            return True
        except OSError:
            self._mark_disconnected()
            return False
        except Exception as exc:
            self._mark_disconnected()
            _print_exception(exc)
            return False

    def _safe_mqtt_call(self, method_name):
        try:
            self._raw_mqtt_call(method_name)
            return True
        except OSError:
            self._mark_disconnected()
            return False
        except Exception as exc:
            self._mark_disconnected()
            _print_exception(exc)
            return False

    def _raw_mqtt_call(self, method_name, *args):
        method = self._raw_mqtt_method(method_name)
        return method(*args)

    def _raw_mqtt_method(self, method_name):
        method = getattr(self._mqttc, method_name)
        if hasattr(self._mqttc, 'reconnect'):
            cls = self._mqttc.__class__
            bases = getattr(cls, '__bases__', ())
            for base in bases:
                base_method = getattr(base, method_name, None)
                if base_method:
                    return lambda *args: base_method(self._mqttc, *args)
        return method

    def _hook_robust_reconnect(self):
        if not hasattr(self._mqttc, 'reconnect'):
            return
        if self._robust_hooked and self._robust_hooked_client is self._mqttc:
            return
        original = self._mqttc.reconnect
        device = self

        def reconnect_wrapper(*args, **kwargs):
            if device._robust_reconnecting:
                return original(*args, **kwargs)
            device._robust_reconnecting = True
            try:
                result = original(*args, **kwargs)
                device._on_connect()
                return result
            finally:
                device._robust_reconnecting = False

        try:
            self._mqttc.reconnect = reconnect_wrapper
            self._robust_hooked = True
            self._robust_hooked_client = self._mqttc
        except Exception:
            self._robust_hooked = False
            self._robust_hooked_client = None

    def _schedule_reconnect(self):
        self._connected = False
        self._awaiting_echo = False
        self._next_reconnect = ticks_add(ticks_ms(), self._reconnect_delay)
        self._reconnect_delay = min(self._reconnect_delay * 2, self.reconnect_max_ms)

    def _mark_disconnected(self):
        self._connected = False
        self._awaiting_echo = False
        self._close_socket()
        if not self._disconnect_requested:
            self._schedule_reconnect()

    def _close_socket(self):
        sock = getattr(self._mqttc, 'sock', None) if self._mqttc else None
        if sock:
            try:
                sock.close()
            except Exception:
                pass
            try:
                self._mqttc.sock = None
            except Exception:
                pass

    def _send_liveness_probe(self):
        if self.publish(self.will_topic, 'online', retain=True):
            self._awaiting_echo = True
            self._echo_deadline = ticks_add(ticks_ms(), self._echo_timeout_ms)
        else:
            self._mark_disconnected()

    def _ha_status_callback(self, msg):
        self.ha_status = msg
        if msg == 'online':
            self.discover_all()
            for entity in self._entities:
                entity.republish()

    def _availability_callback(self, msg):
        if msg == 'online':
            self._last_echo = ticks_ms()
            self._awaiting_echo = False
        elif msg == 'offline' and self._connected and not self._restoring:
            self.publish(self.will_topic, 'online', retain=True)


class Entity(Device):
    def __init__(self, device, entity_name, **kwargs):
        """
        Create a new entity for the device.

        @param device: The device to which this entity belongs.
        @type device: Device

        @param entity_name: The name of the entity.
        @type entity_name: str

        @param kwargs: Additional configuration parameters for the entity,
        passed directly to the Home Assistant configuration.
        @type kwargs: dict
        """
        self.device = device
        self.device._entities.append(self)
        self.name = entity_name
        self.entity = entity_name.replace(' ', '_').lower()
        self.unique_id = "%s_%s" % (self.device.id, self.entity)
        self.topic_prefix = '%s/%s/%s' % (self.device.discovery_prefix, self.entity_type, self.device.id)
        self.discovery_topic = '%s/%s/config' % (self.topic_prefix, self.entity)
        self.topic = '%s/state/%s' % (self.topic_prefix, self.entity)
        self._state_payloads = {}
        self.conf = self.make_conf(**kwargs)

    def make_conf(self, **kwargs):
        """
        Internal method to generate a configuration dictionary for the entity.

        @param kwargs: Additional configuration parameters to be added to the dictionary.

        @return: A dictionary containing the configuration for the entity.
            - "name": The name of the entity.
            - "dev": The device identifier.
            - "uniq_id": The unique identifier for the entity.
            - "avty_t": The availability topic for the device.
            - "stat_t": The state topic for sensors, binary sensors and numbers.
            - "cmd_t": The command topic for buttons and numbers.
        """
        conf = {
            "name": self.name,
            "dev": self.device.device,
            "uniq_id": self.unique_id,
            "avty_t": self.device.will_topic,
        }
        if self.entity_type == 'sensor' or self.entity_type == 'binary_sensor':
            conf["stat_t"] = self.topic
        elif self.entity_type == 'button':
            conf["cmd_t"] = self.topic
        for arg, value in kwargs.items():
            conf[arg] = value
        return conf

    def discover(self):
        """
        @brief Publishes the entity configuration to Home Assistant.

        @return: True on publish success, False if MQTT is currently unavailable.
        """
        payload = json.dumps(self.conf).encode('utf-8')
        return self.device.publish(self.discovery_topic, payload, retain=self.device.retain_discovery)

    def topic_for(self, suffix):
        """
        @brief Builds a topic below this entity's topic prefix.

        @param suffix: Suffix to append to the entity topic prefix.
        @type suffix: str

        @return: Full MQTT topic string.
        """
        suffix = str(suffix).strip('/')
        if suffix:
            return '%s/%s/%s' % (self.topic_prefix, suffix, self.entity)
        return '%s/%s' % (self.topic_prefix, self.entity)

    def _subscribe(self, topic, callback):
        """
        @brief Registers an entity subscription through the parent device.
        """
        return self.device.subscribe(topic, callback)

    def _publish_state(self, payload, topic=None, retain=False, force=False):
        """
        @brief Publishes and caches an entity state payload.

        @param payload: Payload to convert to string and publish.
        @param topic: Optional topic. Defaults to this entity's state topic.
        @param retain: Retain flag. Defaults to False.
        @param force: Publish even if the cached payload did not change. Defaults to False.

        @return: True if a publish was performed successfully or skipped as unchanged,
        False if MQTT is unavailable.

        The payload is cached even when disconnected so reconnect recovery can
        re-publish the most recent known state.
        """
        if topic is None:
            topic = self.conf.get('stat_t', self.topic)
        topic = _to_str(topic)
        payload = str(payload)
        previous = self._state_payloads.get(topic)
        self._state_payloads[topic] = (payload, retain)
        if not force and previous and previous[0] == payload:
            return True
        return self.device.publish(topic, payload, retain=retain)

    def republish(self):
        """
        @brief Force re-publishes all cached state topics for this entity.

        @return: True if all cached states were published or there were none, else False.
        """
        ok = True
        for topic, cached in list(self._state_payloads.items()):
            payload, retain = cached
            if not self._publish_state(payload, topic=topic, retain=retain, force=True):
                ok = False
        return ok


class Select(Entity):
    """
    MQTT Select entity.

    Example:
        mode = uhome.Select(device, 'Mode', ['off', 'eco', 'boost'])
        mode.set_action(lambda value: apply_mode(value))
        mode.publish('eco')

    More information about MQTT Select: https://www.home-assistant.io/integrations/select.mqtt/
    """

    entity_type = 'select'
    _action = None

    def __init__(self, device, entity_name, options, **kwargs):
        self.options = options
        super().__init__(device, entity_name, **kwargs)

    def make_conf(self, **kwargs):
        conf = super().make_conf(**kwargs)
        conf['stat_t'] = self.topic
        conf['cmd_t'] = self.topic_for('set')
        conf['ops'] = list(self.options)
        return conf

    def publish(self, payload, force=False):
        """
        @brief Publishes the selected option to the MQTT state topic if it changed.
        """
        return self._publish_state(payload, self.conf['stat_t'], force=force)

    def get_topic(self):
        return self.conf['cmd_t']

    def set_action(self, action):
        """
        @brief Set the action to be performed when Home Assistant selects a new option.
        """
        self._action = action
        return self._subscribe(self.conf['cmd_t'], self._handle_action)

    def _handle_action(self, msg):
        if self._action:
            self._action(msg)


class Text(Entity):
    """
    MQTT Text entity.

    Example:
        label = uhome.Text(device, 'Display Text', mode='text')
        label.set_action(lambda value: update_display(value))
        label.publish('Ready')

    More information about MQTT Text: https://www.home-assistant.io/integrations/text.mqtt/
    """

    entity_type = 'text'
    _action = None

    def make_conf(self, **kwargs):
        conf = super().make_conf(**kwargs)
        conf['stat_t'] = self.topic
        conf['cmd_t'] = self.topic_for('set')
        return conf

    def publish(self, payload, force=False):
        """
        @brief Publishes the text value to the MQTT state topic if it changed.
        """
        return self._publish_state(payload, self.conf['stat_t'], force=force)

    def get_topic(self):
        return self.conf['cmd_t']

    def set_action(self, action):
        """
        @brief Set the action to be performed when Home Assistant sends new text.
        """
        self._action = action
        return self._subscribe(self.conf['cmd_t'], self._handle_action)

    def _handle_action(self, msg):
        if self._action:
            self._action(msg)


class Scene(Entity):
    """
    MQTT Scene entity.

    Example:
        night = uhome.Scene(device, 'Night Mode')
        night.set_action(lambda payload: apply_night_mode())

    More information about MQTT Scene: https://www.home-assistant.io/integrations/scene.mqtt/
    """

    entity_type = 'scene'
    _action = None

    def make_conf(self, **kwargs):
        conf = super().make_conf(**kwargs)
        conf['cmd_t'] = self.topic_for('set')
        return conf

    def get_topic(self):
        return self.conf['cmd_t']

    def set_action(self, action):
        """
        @brief Set the action to be performed when Home Assistant activates the scene.
        """
        self._action = action
        return self._subscribe(self.conf['cmd_t'], self._handle_action)

    def _handle_action(self, msg):
        if self._action:
            self._action(msg)


class Siren(Entity):
    """
    MQTT Siren entity.

    Example:
        alarm = uhome.Siren(device, 'Alarm Siren')
        alarm.set_action(lambda payload: set_siren(payload == 'ON'))
        alarm.publish('OFF')

    More information about MQTT Siren: https://www.home-assistant.io/integrations/siren.mqtt/
    """

    entity_type = 'siren'
    _action = None

    def make_conf(self, **kwargs):
        conf = super().make_conf(**kwargs)
        conf['stat_t'] = self.topic
        conf['cmd_t'] = self.topic_for('set')
        return conf

    def publish(self, payload, force=False):
        """
        @brief Publishes the siren state to the MQTT state topic if it changed.
        """
        return self._publish_state(payload, self.conf['stat_t'], force=force)

    def get_topic(self):
        return self.conf['cmd_t']

    def set_action(self, action):
        """
        @brief Set the action to be performed when Home Assistant commands the siren.
        """
        self._action = action
        return self._subscribe(self.conf['cmd_t'], self._handle_action)

    def _handle_action(self, msg):
        if self._action:
            self._action(msg)


class Sensor(Entity):
    """
    More information about MQTT Sensors: https://www.home-assistant.io/integrations/sensor.mqtt/
    """

    entity_type = 'sensor'

    def publish(self, payload, force=False):
        """
        @brief Publishes a payload to the MQTT state topic if it changed.

        @param payload: The data to be published. It will be converted to a string before publishing.
        @param force: Publish even if the payload did not change. Defaults to False.
        """
        return self._publish_state(payload, self.conf['stat_t'], force=force)


class BinarySensor(Entity):
    """
    More information about MQTT Binary Sensors: https://www.home-assistant.io/integrations/binary_sensor.mqtt/
    """

    entity_type = 'binary_sensor'

    def publish(self, payload, force=False):
        """
        @brief Publishes a payload to the MQTT state topic if it changed.

        @param payload: The data to be published. It will be converted to a string before publishing.
        @param force: Publish even if the payload did not change. Defaults to False.
        """
        return self._publish_state(payload, self.conf['stat_t'], force=force)


class Button(Entity):
    """
    More information about MQTT Buttons: https://www.home-assistant.io/integrations/button.mqtt/
    """

    entity_type = 'button'
    _action = None

    def get_topic(self):
        return self.conf['cmd_t']

    def set_action(self, action):
        """
        @brief Set the action to be performed when the button is pressed.

        This method subscribes to the command topic specified in the configuration
        and sets the action to be executed when a message is received on that topic.

        @param action: A callable that takes one argument, the message received.
        """
        self._action = action
        return self._subscribe(self.conf['cmd_t'], self._handle_action)

    def _handle_action(self, msg):
        if self._action:
            self._action(msg)


class Switch(Entity):
    """
    MQTT switch entity.

    Example:
        relay = uhome.Switch(device, 'Relay')
        relay.set_action(lambda msg: relay.publish(msg == 'ON'))
        relay.publish(False)

    More information about MQTT Switch: https://www.home-assistant.io/integrations/switch.mqtt/
    """

    entity_type = 'switch'
    _action = None

    def make_conf(self, **kwargs):
        conf = super().make_conf(**kwargs)
        conf['stat_t'] = self.topic_for('state')
        conf['cmd_t'] = self.topic_for('set')
        if 'pl_on' not in conf:
            conf['pl_on'] = 'ON'
        if 'pl_off' not in conf:
            conf['pl_off'] = 'OFF'
        return conf

    def publish(self, state, force=False):
        """
        @brief Publish the switch state.

        @param state: True/'ON' for on, False/'OFF' for off, or a custom payload.
        @param force: Publish even if the payload did not change. Defaults to False.
        """
        if state is True:
            payload = self.conf.get('pl_on', 'ON')
        elif state is False:
            payload = self.conf.get('pl_off', 'OFF')
        else:
            payload = state
        return self._publish_state(payload, self.conf['stat_t'], force=force)

    def on(self, force=False):
        return self.publish(True, force=force)

    def off(self, force=False):
        return self.publish(False, force=force)

    def get_topic(self):
        return self.conf['cmd_t']

    def set_action(self, action):
        """
        @brief Set the action to perform when Home Assistant commands the switch.

        @param action: Callable receiving the command payload string.
        """
        self._action = action
        return self._subscribe(self.conf['cmd_t'], self._handle_action)

    def _handle_action(self, msg):
        if self._action:
            self._action(msg)


class Light(Entity):
    """
    MQTT light entity using Home Assistant's JSON schema.

    Example:
        lamp = uhome.Light(device, 'Lamp', color_temp=True, rgb=True)
        lamp.set_action(lambda cmd: lamp.publish(cmd.get('state', 'OFF'),
                                                 brightness=cmd.get('brightness')))
        lamp.publish('ON', brightness=128)

    More information about MQTT Light: https://www.home-assistant.io/integrations/light.mqtt/
    """

    entity_type = 'light'
    _action = None

    def __init__(self, device, entity_name, color_temp=False, rgb=False, **kwargs):
        self._has_color_temp = color_temp
        self._has_rgb = rgb
        super().__init__(device, entity_name, **kwargs)

    def make_conf(self, **kwargs):
        conf = super().make_conf(**kwargs)
        conf['schema'] = 'json'
        conf['stat_t'] = self.topic_for('state')
        conf['cmd_t'] = self.topic_for('set')
        if 'brightness' not in conf:
            conf['brightness'] = True
        if self._has_color_temp and 'color_temp' not in conf:
            conf['color_temp'] = True
        if self._has_rgb and 'rgb' not in conf:
            conf['rgb'] = True
        return conf

    def publish(self, state, brightness=None, color_temp=None, rgb=None, force=False):
        """
        @brief Publish the light JSON state.

        @param state: True/'ON' for on or False/'OFF' for off.
        @param brightness: Optional 0-255 brightness.
        @param color_temp: Optional color temperature value.
        @param rgb: Optional (red, green, blue) tuple/list.
        @param force: Publish even if the payload did not change. Defaults to False.
        """
        if state is True:
            state = 'ON'
        elif state is False:
            state = 'OFF'
        payload = {'state': state}
        if brightness is not None:
            payload['brightness'] = brightness
        if color_temp is not None:
            payload['color_temp'] = color_temp
        if rgb is not None:
            payload['color'] = {'r': rgb[0], 'g': rgb[1], 'b': rgb[2]}
        return self._publish_state(json.dumps(payload), self.conf['stat_t'], force=force)

    def on(self, brightness=None, color_temp=None, rgb=None, force=False):
        return self.publish('ON', brightness=brightness, color_temp=color_temp, rgb=rgb, force=force)

    def off(self, force=False):
        return self.publish('OFF', force=force)

    def get_topic(self):
        return self.conf['cmd_t']

    def set_action(self, action):
        """
        @brief Set the action to perform when Home Assistant commands the light.

        @param action: Callable receiving the decoded JSON command dictionary.
        """
        self._action = action
        return self._subscribe(self.conf['cmd_t'], self._handle_action)

    def _handle_action(self, msg):
        if self._action:
            try:
                command = json.loads(msg)
            except ValueError:
                command = {'state': msg}
            self._action(command)


class Lock(Entity):
    """
    MQTT lock entity.

    Example:
        door = uhome.Lock(device, 'Front Door')
        door.set_action(lambda msg: door.publish(msg == 'LOCK'))
        door.publish(False)

    More information about MQTT Lock: https://www.home-assistant.io/integrations/lock.mqtt/
    """

    entity_type = 'lock'
    _action = None

    def make_conf(self, **kwargs):
        conf = super().make_conf(**kwargs)
        conf['stat_t'] = self.topic_for('state')
        conf['cmd_t'] = self.topic_for('set')
        if 'pl_lock' not in conf:
            conf['pl_lock'] = 'LOCK'
        if 'pl_unlk' not in conf:
            conf['pl_unlk'] = 'UNLOCK'
        if 'stat_locked' not in conf:
            conf['stat_locked'] = 'LOCKED'
        if 'stat_unlocked' not in conf:
            conf['stat_unlocked'] = 'UNLOCKED'
        return conf

    def publish(self, locked, force=False):
        """
        @brief Publish the lock state.

        @param locked: True/'LOCKED' for locked, False/'UNLOCKED' for unlocked, or a custom payload.
        @param force: Publish even if the payload did not change. Defaults to False.
        """
        if locked is True:
            payload = self.conf.get('stat_locked', 'LOCKED')
        elif locked is False:
            payload = self.conf.get('stat_unlocked', 'UNLOCKED')
        else:
            payload = locked
        return self._publish_state(payload, self.conf['stat_t'], force=force)

    def locked(self, force=False):
        return self.publish(True, force=force)

    def unlocked(self, force=False):
        return self.publish(False, force=force)

    def get_topic(self):
        return self.conf['cmd_t']

    def set_action(self, action):
        """
        @brief Set the action to perform when Home Assistant commands the lock.

        @param action: Callable receiving the command payload string.
        """
        self._action = action
        return self._subscribe(self.conf['cmd_t'], self._handle_action)

    def _handle_action(self, msg):
        if self._action:
            self._action(msg)


class Fan(Entity):
    """
    MQTT fan entity with optional percentage, preset, oscillation and direction features.

    Example:
        fan = uhome.Fan(device, 'Ceiling Fan', percentage=True,
                        preset_modes=['auto', 'sleep'], oscillation=True, direction=True)
        fan.set_action(lambda feature, msg: print(feature, msg))
        fan.publish(True)
        fan.publish_percentage(50)

    More information about MQTT Fan: https://www.home-assistant.io/integrations/fan.mqtt/
    """

    entity_type = 'fan'
    _action = None

    def __init__(self, device, entity_name, percentage=False, preset_modes=None, oscillation=False, direction=False, **kwargs):
        self._has_percentage = percentage
        self._preset_modes = preset_modes
        self._has_oscillation = oscillation
        self._has_direction = direction
        super().__init__(device, entity_name, **kwargs)

    def make_conf(self, **kwargs):
        conf = super().make_conf(**kwargs)
        conf['stat_t'] = self.topic_for('state')
        conf['cmd_t'] = self.topic_for('set')
        if 'pl_on' not in conf:
            conf['pl_on'] = 'ON'
        if 'pl_off' not in conf:
            conf['pl_off'] = 'OFF'
        if self._has_percentage:
            conf['pct_stat_t'] = self.topic_for('percentage/state')
            conf['pct_cmd_t'] = self.topic_for('percentage/set')
        if self._preset_modes:
            conf['pr_modes'] = self._preset_modes
            conf['pr_mode_stat_t'] = self.topic_for('preset_mode/state')
            conf['pr_mode_cmd_t'] = self.topic_for('preset_mode/set')
        if self._has_oscillation:
            conf['osc_stat_t'] = self.topic_for('oscillation/state')
            conf['osc_cmd_t'] = self.topic_for('oscillation/set')
            if 'pl_osc_on' not in conf:
                conf['pl_osc_on'] = 'oscillate_on'
            if 'pl_osc_off' not in conf:
                conf['pl_osc_off'] = 'oscillate_off'
        if self._has_direction:
            conf['dir_stat_t'] = self.topic_for('direction/state')
            conf['dir_cmd_t'] = self.topic_for('direction/set')
        return conf

    def publish(self, state, force=False):
        """
        @brief Publish the fan on/off state.
        """
        if state is True:
            payload = self.conf.get('pl_on', 'ON')
        elif state is False:
            payload = self.conf.get('pl_off', 'OFF')
        else:
            payload = state
        return self._publish_state(payload, self.conf['stat_t'], force=force)

    def on(self, force=False):
        return self.publish(True, force=force)

    def off(self, force=False):
        return self.publish(False, force=force)

    def publish_percentage(self, percentage, force=False):
        return self._publish_state(percentage, self.conf['pct_stat_t'], force=force)

    def publish_preset_mode(self, preset_mode, force=False):
        return self._publish_state(preset_mode, self.conf['pr_mode_stat_t'], force=force)

    def publish_oscillation(self, oscillating, force=False):
        if oscillating is True:
            payload = self.conf.get('pl_osc_on', 'oscillate_on')
        elif oscillating is False:
            payload = self.conf.get('pl_osc_off', 'oscillate_off')
        else:
            payload = oscillating
        return self._publish_state(payload, self.conf['osc_stat_t'], force=force)

    def publish_direction(self, direction, force=False):
        return self._publish_state(direction, self.conf['dir_stat_t'], force=force)

    def get_topic(self):
        return self.conf['cmd_t']

    def set_action(self, action):
        """
        @brief Set the action to perform when Home Assistant commands the fan.

        @param action: Callable receiving feature name and payload string.
        """
        self._action = action
        ok = self._subscribe(self.conf['cmd_t'], self._handle_state_command)
        if 'pct_cmd_t' in self.conf and not self._subscribe(self.conf['pct_cmd_t'], self._handle_percentage_command):
            ok = False
        if 'pr_mode_cmd_t' in self.conf and not self._subscribe(self.conf['pr_mode_cmd_t'], self._handle_preset_mode_command):
            ok = False
        if 'osc_cmd_t' in self.conf and not self._subscribe(self.conf['osc_cmd_t'], self._handle_oscillation_command):
            ok = False
        if 'dir_cmd_t' in self.conf and not self._subscribe(self.conf['dir_cmd_t'], self._handle_direction_command):
            ok = False
        return ok

    def _dispatch(self, feature, msg):
        if self._action:
            self._action(feature, msg)

    def _handle_state_command(self, msg):
        self._dispatch('state', msg)

    def _handle_percentage_command(self, msg):
        self._dispatch('percentage', msg)

    def _handle_preset_mode_command(self, msg):
        self._dispatch('preset_mode', msg)

    def _handle_oscillation_command(self, msg):
        self._dispatch('oscillation', msg)

    def _handle_direction_command(self, msg):
        self._dispatch('direction', msg)


class Number(Entity):
    """
    More information about MQTT Number: https://www.home-assistant.io/integrations/number.mqtt/

    Example:
        level = Number(device, "Target Level", min=0, max=100, step=5)
        level.set_action(lambda value: level.publish(value))
        level.publish(50)
    """

    entity_type = 'number'
    _action = None

    def make_conf(self, **kwargs):
        conf = Entity.make_conf(self, **kwargs)
        conf["stat_t"] = self.topic
        conf["cmd_t"] = self.topic_for('set')
        return conf

    def publish(self, payload, force=False):
        """
        @brief Publishes a payload to the MQTT state topic if it changed.

        @param payload: The data to be published. It will be converted to a string before publishing.
        @param force: Publish even if the payload did not change. Defaults to False.
        """
        return self._publish_state(payload, self.conf['stat_t'], force=force)

    def get_topic(self):
        return self.conf['cmd_t']

    def set_action(self, action):
        """
        @brief Set the action to be performed when the number value is changed.

        This method subscribes to the command topic specified in the configuration
        and sets the action to be executed when a message is received on that topic.

        @param action: A callable that takes one argument, the message received with the new number value.
        """
        self._action = action
        return self._subscribe(self.conf['cmd_t'], self._handle_action)

    def _handle_action(self, msg):
        if self._action and self._is_valid_value(msg):
            self._action(msg)

    def _is_valid_value(self, msg):
        try:
            value = float(msg)
        except (TypeError, ValueError):
            return False

        min_value = self.conf.get('min')
        max_value = self.conf.get('max')
        step = self.conf.get('step')

        try:
            if min_value is not None and value < float(min_value):
                return False
            if max_value is not None and value > float(max_value):
                return False
            if step is not None:
                step = float(step)
                if step <= 0:
                    return False
                base = float(min_value) if min_value is not None else 0.0
                steps = (value - base) / step
                nearest = round(steps)
                if abs(steps - nearest) > 0.000001:
                    return False
        except (TypeError, ValueError):
            return False
        return True


class WaterHeater(Entity):
    """
    MQTT water heater entity.

    Example:
        heater = uhome.WaterHeater(device, 'Boiler', modes=['off', 'eco', 'performance'])
        heater.set_mode_action(lambda mode: set_mode(mode))
        heater.set_temperature_action(lambda value: set_target(float(value)))
        heater.publish_mode('eco')
        heater.publish_target_temperature(55)
        heater.publish_current_temperature(48)

    More information: https://www.home-assistant.io/integrations/water_heater.mqtt/
    """

    entity_type = 'water_heater'
    _mode_action = None
    _temperature_action = None

    def make_conf(self, **kwargs):
        conf = super().make_conf(**kwargs)
        conf['mode_stat_t'] = self.topic_for('mode/state')
        conf['mode_cmd_t'] = self.topic_for('mode/set')
        conf['temp_stat_t'] = self.topic_for('temperature/state')
        conf['temp_cmd_t'] = self.topic_for('temperature/set')
        conf['curr_temp_t'] = self.topic_for('current_temperature/state')
        return conf

    def publish_mode(self, mode, force=False):
        """Publish the current operation mode."""
        return self._publish_state(mode, self.conf['mode_stat_t'], force=force)

    def publish_target_temperature(self, temperature, force=False):
        """Publish the target temperature."""
        return self._publish_state(temperature, self.conf['temp_stat_t'], force=force)

    def publish_current_temperature(self, temperature, force=False):
        """Publish the measured current temperature."""
        return self._publish_state(temperature, self.conf['curr_temp_t'], force=force)

    def get_mode_topic(self):
        return self.conf['mode_cmd_t']

    def get_temperature_topic(self):
        return self.conf['temp_cmd_t']

    def set_mode_action(self, action):
        """Set the callback for water heater mode commands."""
        self._mode_action = action
        return self._subscribe(self.conf['mode_cmd_t'], self._handle_mode)

    def set_temperature_action(self, action):
        """Set the callback for target temperature commands."""
        self._temperature_action = action
        return self._subscribe(self.conf['temp_cmd_t'], self._handle_temperature)

    def _handle_mode(self, msg):
        if self._mode_action:
            self._mode_action(msg)

    def _handle_temperature(self, msg):
        if self._temperature_action:
            self._temperature_action(msg)


class AlarmControlPanel(Entity):
    """
    MQTT alarm control panel entity.

    Example:
        alarm = uhome.AlarmControlPanel(device, 'Alarm')
        alarm.set_action(lambda payload: handle_alarm_command(payload))
        alarm.publish('armed_away')

    More information: https://www.home-assistant.io/integrations/alarm_control_panel.mqtt/
    """

    entity_type = 'alarm_control_panel'
    _action = None

    def make_conf(self, **kwargs):
        conf = super().make_conf(**kwargs)
        conf['stat_t'] = self.topic_for('state')
        conf['cmd_t'] = self.topic_for('set')
        return conf

    def publish(self, state, force=False):
        """Publish the alarm state."""
        return self._publish_state(state, self.conf['stat_t'], force=force)

    def get_topic(self):
        return self.conf['cmd_t']

    def set_action(self, action):
        """Set the callback for alarm command payloads."""
        self._action = action
        return self._subscribe(self.conf['cmd_t'], self._handle_action)

    def _handle_action(self, msg):
        if self._action:
            self._action(msg)
